apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: flex-gateway-test
spec:
  address: http://0.0.0.0:8000
  services:
    flex-gateway-test:
      address: http://flex-gateway-test.us-e2.cloudhub.io
      routes:
        - rules:
            - {}
  policies:
    - policyRef:
        name: http-basic-authentication-flex
      config:
        username: test
        password: test
    - policyRef:
        name: rate-limiting-flex
      config:
        exposeHeaders: true
        rateLimits:
          - maximumRequests: 2
            timePeriodInMilliseconds: 6000
        keySelector: #[attributes.queryParams['identifier']]
