apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: flex-gateway-test
spec:
  address: http://0.0.0.0:8000
  services:
    flex:
      address: http://flex-gateway-test.us-e2.cloudhub.io/flex/api
      routes:
        - rules:
            - path: /flex/api(/.*)
  policies:
    - policyRef: http-basic-authentication-flex
      config:
        username: basil
        password: basil
    - policyRef: rate-limiting
      config:
        exposeHeaders: true
        rateLimits:
          - maximumRequests: 3
            timePeriodInMilliseconds: 6000
        keySelector: #[attributes.queryParams['identifier']]
